### ISSUE TITLE
Empty promise array for `Promise.all` and `Promise.any` never settle

### ISSUE THREAD

**Issue by bryanmylee** [TheWalruzz/godot-promise#1]
Passing an empty array for either `Promise.all` or `Promise.any` results in a promise that never resolves.

```gdscript
await Promise.all([]).settled # hangs
await Promise.any([]).settled # hangs
```

Ideally, `Promise.all([])` should immediately resolve with an empty value `[]`, and `Promise.any([])` should immediately reject with an error requiring at least one promise to be passed.

**Comment by TheWalruzz** [comment]
Good catch, I'll prepare a fix for that tomorrow

**Comment by TheWalruzz** [comment]
Ok, the fix is done. I'll update the Asset Library entry shortly. Closing the issue unless something new comes up
