### ISSUE TITLE
Signal Emitted in same function call as the promise does not get settled

### ISSUE THREAD

**Issue by accidentallyc** [TheWalruzz/godot-promise#2]
Hi there, awesome library and thanks for this!

There's a use case I want to replicate with Promises, but i've not been able to figure it out using the library without hacking it 

Javascript
```javascript
void async function main() {
    var promise = Promise.resolve("resolved")
    await promise.then(() => console.log("Resolved right after"))
    setTimeout(async function () {
        await promise
        console.log("Resolved even after promise has been initally resolved")
    },500)
}()

/*
Output:
Resolved right after
Resolved even after promise has been initally resolved
*/
```

In that js recreation example, i'm able to keep resolving a Promise that has been resolved waaay back

I tried to recreate a similar code in gdscript

```gdscript
var new_promise = Promise.new(func (resolve:Callable,reject): resolve.call(true))
        
func _ready():
    await new_promise.settled
    print("Resolved right after")
    await get_tree().create_timer(0.5).timeout
    await new_promise.settled
    print("Resolved even after promise has been initally resolved")

"""
Output:
Resolved right after
"""
```

However in the gd example, the second new_promise await doesnt work, and after digging through the code, this is very likely because it uses signals underneath the hood

But im wondering if it would be possible to do what im asking for without any code changes?

**Comment by TheWalruzz** [comment]
I believe this is due to the implementation being based on one-shot signal emission and not being stored anywhere. I might not find time to take a deeper look right now, but I'll get to it soon

**Comment by TheWalruzz** [comment]
Ok, it required a slight change of API (but old code should still work fine!), but Promises now expose `wait()` method that you can use instead of `settled` signal. It also now works if you add `then()` or `catch()` to an already settled Promise.

Also, I added `Promise.resolve` and `Promise.reject` - I'm not sure why I omitted them before 😅
