### ISSUE TITLE
from_many() fails to return Array[Signal]

### ISSUE THREAD

**Issue by GameDev-One** [TheWalruzz/godot-promise#3]
The method `from_many()` does not return `Array[Signal]` because it cannot convert a generic array into a typed array. This is a known issue in Godot, and it may be resolved in a future update. 

A recommended workaround is to use `Array.assign()` to convert the array to the correct type. 

https://github.com/godotengine/godot/issues/72566

**Comment by GameDev-One** [comment]
```gdscript
static func from_many(input_signals: Array[Signal]) -> Array[Promise]:
	var typed_input_signals: Array[Promise]
	typed_input_signals.assign(input_signals.map(
	    func(input_signal: Signal): 
	        return Promise.From(input_signal)
		    )
		)
	return typed_input_signals
```

**Comment by TheWalruzz** [comment]
Ugh, I need to fix the GdUnit setup to catch those issues...

Nevertheless, thanks for letting me know!

**Comment by GameDev-One** [comment]
No worries! 😁 
I've enjoyed how useful this plugin is and could see it becoming a mainstay for all of my future projects.
